services:
  - type: web
    name: pentouz
    runtime: node
    buildCommand: npm install && npm run build && cp -r public .next/standalone/ && cp -r .next/static .next/standalone/.next/
    startCommand: node .next/standalone/server.js
    envVars:
      - key: NODE_VERSION
        value: "18"
      - key: PORT
        value: "10000"
      - key: HOSTNAME
        value: "0.0.0.0"
